### ISSUE TITLE
3.0 throw EOFError: Ran out of input, but works in 2.0 

### ISSUE THREAD

**Issue by DingXiangYuanZhiXing** [MolecularAI/GraphINVENT#8]
The code before 2.0 works well. But in 3.0, I try to run `submit-pre-training.py` and `submit-fine-tune.py` both give me this error. I try to change the `job_type` in the former version of `submit.py`, which also doesn't work.
![image](https://user-images.githubusercontent.com/28868457/131390079-a2d2baf9-edf4-4a13-b7a6-47d2433a87bc.png)
Did I miss anything need to do before run these 2 python scripts?

**Comment by rociomer** [comment]
Try again, it should work now.

The program was trying to read the QSAR model specified in defaults.py under the "QSAR_models" key in the parameters dictionary. It does this in `constants.py`, but I have changed it now so that it only tries to load a QSAR model during a fine-tuning job. In that case, it will try to load the models specified in the parameters dictionary, I have left the following path as an example in `defaults.py`: 

```
"qsar_models"         : {"drd2_activity": "data/fine-tuning/qsar_model.pickle"},
```

but if you do want to use it you will have to download the QSAR model (from https://github.com/pcko1/Deep-Drug-Coder) to the specified directory before running the code. This path can also be modified in `submit-fine-tune.py`

Does this answer your question?
Sorry, I have not gotten around yet to writing an RL tutorial for GraphINVENT... but I hope to soon!

**Comment by DingXiangYuanZhiXing** [comment]
![image](https://user-images.githubusercontent.com/28868457/132140835-b5e12c14-8858-4be3-b25f-bd26fe44ede4.png)
I got this new bug and I solved it by changing from `torch.Tensor` to `torch.tensor`.
